
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
  # labels:
  #   argocd-image-updater.argoproj.io/enabled: "true"
   #annotations:    
    # argocd-image-updater.argoproj.io/image-list: app=lehardocker/gitops-coupon-app
    # argocd-image-updater.argoproj.io/app.update-strategy: latest
  #   argocd-image-updater.argoproj.io/app.allow-tags: regexp:^[a-f0-9]{7}$
  #   argocd-image-updater.argoproj.io/write-back-method: git
  #   argocd-image-updater.argoproj.io/git-branch: master    
  #   argocd-image-updater.argoproj.io/app.pull-secret: pullsecret:argocd/repo-git-creds
  #   argocd-image-updater.argoproj.io/app.force-update: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/sureshkumar-devops/gitops-coupon-app.git
    targetRevision: master
    path: k8s
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
